"""Offline tests for the user interfaces and optional LLM."""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

import httpx
import pytest

from sachet.cli import main
from sachet.gateway import SerpGateway
from sachet.llm import LLM
from sachet.models import Finding, Offer, Severity, Source
from sachet.planner import Agent
from sachet.report import to_markdown, to_terminal
from sachet.web import InvestigationRequest, create_app

COMPANY = "Kavera Analytics Pvt Ltd"
FIXTURES = Path(__file__).parent / "fixtures" / "synthetic"


def mocked_llm(*replies):
    calls = iter(replies)

    def handler(request):
        assert request.url.path == "/v1/chat/completions"
        return httpx.Response(200, json={"choices": [{"message": next(calls)}]})

    return LLM("https://llm.example/v1", "test", transport=httpx.MockTransport(handler))


def test_refine_fills_only_blank_fields():
    offer = Offer("Hello", company="Original", emails=["x@example.com"])
    llm = mocked_llm({"content": json.dumps({"company": "Wrong", "role": "Analyst",
                                               "city": "Pune", "address": "Office A"})})
    refined = llm.refine(offer)
    assert (refined.company, refined.role, refined.city, refined.address) == (
        "Original", "Analyst", "Pune", "Office A")
    assert refined.emails == offer.emails


@pytest.mark.parametrize("content", ["bad json", "[]", "null"])
def test_refine_bad_json_keeps_offer(content):
    offer = Offer("Hello")
    assert mocked_llm({"content": content}).refine(offer) is offer


def test_llm_http_failure_keeps_offer():
    llm = LLM(transport=httpx.MockTransport(lambda request: httpx.Response(503)))
    offer = Offer("Hello")
    assert llm.refine(offer) is offer


def test_llm_investigate_and_planner_citation_filter():
    url = "https://kavera-analytics.in/careers"
    llm = mocked_llm({"content": "{}"}, {"content": json.dumps({"findings": [
        {"severity": "high", "title": "Cited", "detail": "Evidence", "source_urls": [url]},
        {"severity": "medium", "title": "Uncited", "detail": "No source", "source_urls": []},
        {"severity": "high", "title": "Invented", "detail": "Wrong", "source_urls": ["https://fake.test"]},
    ]})}, {"content": json.dumps({"summary": "Only a cited concern was found."})})
    report = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None)).run(
        Offer("", company=COMPANY), llm=llm)
    assert [f.title for f in report.findings if f.origin == "llm"] == ["Cited"]
    assert report.dropped_llm_findings == 2
    assert report.to_dict()["dropped_llm_findings"] == 2
    assert report.summary == "Only a cited concern was found."


@pytest.mark.parametrize("content", ["bad", "{}", '{"findings": "wrong"}'])
def test_llm_investigate_malformed_returns_empty(content):
    llm = mocked_llm({"content": content})
    agent = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None))
    agent.run(Offer("", company=COMPANY))
    assert llm.investigate(agent.last_investigation) == []


def test_llm_tool_call_limited_to_three():
    requests = []

    def handler(request):
        body = json.loads(request.content)
        requests.append(body)
        if len(requests) == 1:
            return httpx.Response(200, json={"choices": [{"message": {"content": None,
                "tool_calls": [{"id": "1", "function": {"name": "web_search",
                "arguments": json.dumps({"query": COMPANY})}}]}}]})
        return httpx.Response(200, json={"choices": [{"message": {"content": '{"findings": []}'}}]})

    llm = LLM("https://llm.example/v1", "x", transport=httpx.MockTransport(handler))
    agent = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None))
    agent.run(Offer("", company=COMPANY))
    assert llm.investigate(agent.last_investigation) == []
    assert len(requests) == 2
    assert requests[1]["messages"][-1]["role"] == "tool"


def test_llm_from_env(monkeypatch):
    monkeypatch.delenv("SACHET_LLM_API_KEY", raising=False)
    monkeypatch.delenv("SACHET_LLM_BASE_URL", raising=False)
    assert LLM.from_env() is None
    monkeypatch.setenv("SACHET_LLM_BASE_URL", "http://localhost:11434/v1")
    assert LLM.from_env() is not None


def test_report_renderers():
    report = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None)).run(
        Offer("", company=COMPANY, emails=["hr@kavera-analytics.in"]))
    md = to_markdown(report)
    terminal = to_terminal(report, color=False)
    assert f"({report.score}/100)" in md
    assert "## Next steps" in md
    assert "Generated by Sachet using live SerpApi results" in md
    assert "https://" in md
    assert "\033[" not in terminal
    assert "Searches:" in terminal
    assert "\033[" in to_terminal(report)


def test_cli_replay_json(capsys):
    import io

    old = sys.stdin
    sys.stdin = io.StringIO(f"Company: {COMPANY}\nRole: Analyst")
    try:
        assert main(["check", "-", "--replay", str(FIXTURES), "--json"]) == 0
    finally:
        sys.stdin = old
    output = capsys.readouterr()
    parsed = json.loads(output.out)
    assert {"score", "verdict", "offer", "findings", "calls", "dropped_llm_findings"} <= parsed.keys()
    assert "step footprint" in output.err


def test_cli_missing_key(monkeypatch, capsys):
    monkeypatch.delenv("SERPAPI_API_KEY", raising=False)
    monkeypatch.delenv("SERPAPI_KEY", raising=False)
    assert main(["check", "--no-cache"]) == 3
    assert "SERPAPI_API_KEY" in capsys.readouterr().err


def test_cli_examples(capsys):
    assert main(["examples"]) == 0
    assert "fake_task_job.txt" in capsys.readouterr().out


def test_web_health_examples(monkeypatch):
    monkeypatch.delenv("SERPAPI_API_KEY", raising=False)
    monkeypatch.delenv("SERPAPI_KEY", raising=False)
    async def check():
        async with httpx.AsyncClient(transport=httpx.ASGITransport(
                app=create_app(replay_dir=FIXTURES)), base_url="http://test") as client:
            assert (await client.get("/api/health")).json()["replay"] is True
            examples = (await client.get("/api/examples")).json()
            assert len(examples) == 3
            assert (await client.get("/")).status_code == 200
            assert "Sachet" in (await client.get("/")).text

    asyncio.run(check())


def test_web_stream_report():
    async def check():
        app = create_app(replay_dir=FIXTURES)
        endpoint = next(route.endpoint for route in app.routes
                        if getattr(route, "path", None) == "/api/investigate")
        response = await endpoint(InvestigationRequest(text=f"Company: {COMPANY}\nRole: Analyst"))
        return [json.loads(line) async for line in response.body_iterator]

    events = asyncio.run(check())
    assert events[0]["type"] == "extracted"
    assert events[-1]["type"] == "report"
    assert "score" in events[-1]["report"]
    assert all("searches_left" in e for e in events if e["type"] == "step")


def test_web_rejects_empty_text():
    async def check():
        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=create_app()),
                                     base_url="http://test") as client:
            return await client.post("/api/investigate", json={"text": ""})

    assert asyncio.run(check()).status_code == 422


def test_planner_unknown_domain_replan():
    gateway = SerpGateway(replay_dir=FIXTURES, cache_dir=None)
    agent = Agent(gateway)
    agent.run(Offer("", company="Zyntrix Careers Hub", emails=["hr@unknown-zyntrix.in"]))
    ctx = agent.last_investigation
    assert "unknown-zyntrix.in" in ctx.suspicious_domains
    assert any(s["name"] == "domain_probe" and s["reason"] ==
               "official site not found, probing recruiter domain" and
               s["added_by"] == "replan" for s in ctx.steps)


def test_planner_budget_override():
    gateway = SerpGateway(replay_dir=FIXTURES, budget=1, cache_dir=None)
    Agent(gateway).run(Offer("", company=COMPANY), budget=3)
    assert gateway.budget == 3
    Agent(gateway).run(Offer("", company=COMPANY), budget=None)
    assert gateway.budget == 3


def test_planner_drops_llm_with_no_sources():
    class Fake:
        def investigate(self, ctx):
            return [Finding("agent", Severity.HIGH, "No citation", "Claim"),
                    Finding("agent", Severity.MEDIUM, "Bad citation", "Claim",
                            [Source("Unknown", "https://unknown.test")])]

    report = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None)).run(
        Offer("", company=COMPANY), llm=Fake())
    assert report.dropped_llm_findings == 2
    assert all(f.origin != "llm" for f in report.findings)


def test_mcp_import_guard(monkeypatch, capsys):
    from sachet import mcp_server

    monkeypatch.setitem(sys.modules, "mcp", None)
    assert mcp_server.main() == 1
    assert 'pip install "sachet[mcp]"' in capsys.readouterr().err


@pytest.mark.parametrize("severity", list(Severity))
def test_report_group_headings(severity):
    report = Agent(SerpGateway(replay_dir=FIXTURES, cache_dir=None)).run(Offer(""))
    report.findings = [Finding("test", severity, "Title", "Detail")]
    assert f"## {severity.value.title()} findings" in to_markdown(report)


def test_mcp_server_registers_tool():
    pytest.importorskip("mcp")
    import asyncio

    from sachet.mcp_server import build_server

    tools = asyncio.run(build_server().list_tools())
    assert [t.name for t in tools] == ["verify_job_offer"]


def test_dotenv_loader(tmp_path, monkeypatch):
    from sachet.envfile import load_dotenv

    monkeypatch.delenv("SACHET_TEST_VALUE", raising=False)
    env = tmp_path / ".env"
    env.write_text('# comment\nexport SACHET_TEST_VALUE="abc"\nBROKEN LINE\n')
    load_dotenv(env)
    import os

    assert os.environ["SACHET_TEST_VALUE"] == "abc"
