"""Human-readable report renderers."""

from __future__ import annotations

from .models import Severity

_ORDER = list(Severity)


def to_markdown(report) -> str:
    lines = [f"# {report.verdict_label} ({report.score}/100)", "", report.summary, ""]
    for severity in _ORDER:
        findings = [f for f in report.findings if f.severity == severity]
        if not findings:
            continue
        lines.extend([f"## {severity.value.title()} findings", ""])
        for finding in findings:
            lines.append(f"- **{finding.title}**: {finding.detail}")
            for source in finding.sources:
                lines.append(f"  - [{source.title}]({source.url})")
        lines.append("")
    used = sum(call.ok and not call.cached for call in report.calls)
    cached = sum(call.ok and call.cached for call in report.calls)
    lines.extend([f"Searches: {used} live, {cached} cached.", "", "## Next steps", ""])
    lines.extend(f"- {step}" for step in report.next_steps)
    lines.extend(["", "Generated by Sachet using live SerpApi results"])
    return "\n".join(lines) + "\n"


def to_terminal(report, color=True) -> str:
    hue = "\033[31m" if report.score >= 60 else "\033[33m" if report.score >= 30 else "\033[32m"
    title = f"{report.verdict_label}  {report.score}/100"
    if color:
        title = f"{hue}{title}\033[0m"
    lines = [title, report.summary]
    for finding in report.findings:
        lines.append(f"  [{finding.severity.value}] {finding.title}: {finding.detail}")
        lines.extend(f"    {source.url}" for source in finding.sources)
    used = sum(call.ok and not call.cached for call in report.calls)
    cached = sum(call.ok and call.cached for call in report.calls)
    lines.append(f"Searches: {used} live, {cached} cached")
    lines.extend(f"Next: {step}" for step in report.next_steps)
    return "\n".join(lines) + "\n"
